import { useEffect, useState } from 'react'
import { Link, Route, Routes, useLocation, useParams } from 'react-router-dom'
import { ArrowRight, Check, ChevronDown, Mail, MapPin, Menu, MessageCircle, Phone, X } from 'lucide-react'

const API = import.meta.env.VITE_API_URL || `${window.location.protocol}//${window.location.hostname}:4000`
const whatsapp = 'https://wa.me/256774497295'
const phone = '+256 788 748 128 / +256 756 037 524'
const services = [
  ['flight-reservations', 'Flight reservations & ticketing', 'Professional booking support for local and international travel enquiries.'],
  ['visa-assistance', 'Visa assistance', 'Clear, careful guidance through the visa application process.'],
  ['hotel-reservations', 'Hotel reservations', 'Reliable stays selected around your route, comfort, and budget.'],
  ['tour-packages', 'Holiday & tour packages', 'Thoughtfully arranged holidays, safaris, honeymoons, and family journeys.'],
  ['travel-insurance', 'Travel insurance', 'Practical travel insurance guidance before you take off.'],
  ['airport-transfers', 'Airport transfers', 'Pick-up and drop-off coordination in Kampala and beyond.'],
  ['corporate-travel', 'Corporate travel management', 'Responsive travel support for businesses, teams, and frequent travellers.'],
  ['family-reunification', 'Family reunification guidance', 'Dedicated travel support for diaspora families planning to reconnect.'],
]
const destinations = [
  ['bwindi', 'Bwindi', 'Uganda', 'Misty rainforest and a remarkable setting for considered travel.', 'bwindi.svg'],
  ['queen-elizabeth', 'Queen Elizabeth', 'Uganda', 'Open savanna, crater lakes, and classic safari country.', 'queen-elizabeth.svg'],
  ['jinja', 'Jinja', 'Uganda', 'River days, rapids, and slow sunsets at the source of the Nile.', 'jinja.svg'],
  ['ssese-islands', 'Ssese Islands', 'Uganda', 'Palm-fringed beaches and quiet lake air reached by ferry.', 'ssese-islands.svg'],
]
const tours = [
  ['gorilla-trek', 'Gorilla Trek', 'Bwindi, Uganda', '5 days', 'A considered journey into Bwindi with expert local guides and time to breathe.', 'gorilla-trek.svg'],
  ['nile-source-adventure', 'Nile Source Adventure', 'Jinja, Uganda', '4 days', 'White water, warm evenings, and the wild pulse of the Nile at its source.', 'nile-adventure.svg'],
  ['classic-savanna-safari', 'Classic Savanna Safari', 'Uganda', '6 days', 'A generous loop through Uganda’s great parks, made for curious travellers.', 'savanna-safari.svg'],
]
const faqs = [
  ['Flight Reservations', 'We provide professional booking support and ticketing assistance based on your travel requirements.'],
  ['Visa Assistance', 'We can guide you through the information and application process. Visa decisions are made by the relevant authorities.'],
  ['Hotel Booking', 'Tell us your route, dates, comfort needs, and preferences so we can help shape an enquiry.'],
  ['Tours & Safaris', 'Our team can help arrange holiday packages and safari enquiries around your needs.'],
  ['Airport Transfers', 'Share your flight, passenger, date, and destination details so we can coordinate a transfer enquiry.'],
  ['General enquiries', 'Use the enquiry form, WhatsApp, phone, or email and our team will respond with next steps.'],
]

function image(path) { return `${API}/images/${path}` }
function slotForPath(path) {
  const [category, filename] = path.split('/')
  const name = filename?.replace(/\.[^.]+$/, '')
  if (category === 'hero') return name === 'sunset-savanna' ? 'hero-secondary' : 'hero'
  if (category === 'destinations') return `destination:${name}`
  if (category === 'tours') return `tour:${name}`
  return null
}
function resolveImage(path, images) { const slot = slotForPath(path); return images?.slots?.[slot]?.url || (slot ? `${API}/images/slot/${slot}?fallback=${encodeURIComponent(path)}` : image(path)) }
function useSiteImages() { const [images, setImages] = useState({}); useEffect(() => { fetch(`${API}/api/images`).then(response => response.json()).then(setImages).catch(() => {}) }, []); return images }
function Meta({ title, description }) { useEffect(() => { document.title = `${title} | Altis Voyage`; let meta = document.querySelector('meta[name="description"]'); if (!meta) { meta = document.createElement('meta'); meta.name = 'description'; document.head.appendChild(meta) } meta.content = description }, [title, description]); return null }
function Img({ src, alt }) { return <img src={src?.startsWith('http') ? src : `${API}${src || ''}`} alt={alt} loading="lazy" /> }
function WhatsApp({ children = 'WhatsApp us' }) { return <a className="whatsapp-cta" href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle size={17} />{children}</a> }
function PageHero({ eyebrow, title, text, imagePath = 'hero/lake-bunyonyi.svg' }) { const images = useSiteImages(); return <section className="platform-hero" style={{ backgroundImage: `linear-gradient(90deg,rgba(6,23,45,.96),rgba(6,23,45,.62)),url(${resolveImage(imagePath, images)})` }}><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{text && <p>{text}</p>}<WhatsApp /></div></section> }
function Breadcrumbs({ current }) { return <div className="breadcrumbs"><Link to="/">Home</Link><span>/</span><span>{current}</span></div> }
function Header() { const [open, setOpen] = useState(false); const location = useLocation(); useEffect(() => setOpen(false), [location.pathname]); return <header className="platform-nav"><Link className="brand" to="/"><img src="/logo.jpg" alt="Altis Voyage Travel" /></Link><button className="platform-menu" onClick={() => setOpen(!open)} aria-label="Open navigation">{open ? <X /> : <Menu />}</button><nav className={open ? 'platform-links open' : 'platform-links'}><Link to="/about">About</Link><Link to="/services">Services</Link><Link to="/destinations">Destinations</Link><Link to="/tours">Tours</Link><Link to="/honeymoon">Honeymoon</Link><Link to="/gallery">Gallery</Link><Link to="/faq">FAQ</Link><Link className="nav-plan" to="/contact">Plan your trip <ArrowRight size={15} /></Link></nav></header> }
function Footer() { return <footer className="platform-footer"><div className="footer-main"><div><Link className="brand" to="/"><img src="/logo.jpg" alt="Altis Voyage Travel" /></Link><p>Professional travel solutions from Kampala, Uganda.</p><WhatsApp /></div><div><h3>Explore</h3><Link to="/about">About us</Link><Link to="/why-choose-us">Why choose us</Link><Link to="/destinations">Destinations</Link><Link to="/tours">Tours & packages</Link><Link to="/travel-resources">Travel resources</Link></div><div><h3>Services</h3>{services.slice(0, 5).map(([slug, name]) => <Link key={slug} to={`/services/${slug}`}>{name}</Link>)}</div><div><h3>Contact</h3><a href="tel:+256788748128"><Phone size={14} /> {phone}</a><a href="mailto:info@altistravels.com"><Mail size={14} /> info@altistravels.com</a><span><MapPin size={14} /> Kampala, Uganda</span><Link to="/contact">Contact centre <ArrowRight size={14} /></Link></div></div><div className="footer-bottom"><span>ALTIS VOYAGE TRAVEL SERVICES LTD · Reg. No. 80034849146981</span><span><Link to="/privacy-policy">Privacy</Link> · <Link to="/terms-and-conditions">Terms</Link></span></div></footer> }
function Shell({ children }) { return <div className="platform"><Header /><main>{children}</main><a className="floating-whatsapp" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp"><MessageCircle /></a><Footer /></div> }
function EnquiryForm({ service = '', destination = '' }) { const [sent, setSent] = useState(false); const [error, setError] = useState(''); async function submit(event) { event.preventDefault(); const form = event.currentTarget; setError(''); try { const values = Object.fromEntries(new FormData(form)); values.destination = values.destination_detail || values.service_required || destination; const response = await fetch(`${API}/api/inquiries`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); if (!response.ok) throw new Error('Unable to send your enquiry.'); setSent(true); form.reset() } catch (err) { setError(err.message) } } if (sent) return <div className="enquiry-success"><Check /><h3>Enquiry received</h3><p>Thank you. Our team will be in touch shortly.</p><div><WhatsApp>Continue on WhatsApp</WhatsApp><a href="mailto:bookings@altistravels.com">Email bookings</a></div></div>; return <form className="travel-enquiry" onSubmit={submit}><div className="form-heading"><p className="tag">Start planning</p><h2>Tell us where you want to go.</h2><p>Share the essentials and we will come back with a considered next step.</p></div><input type="hidden" name="service" value={service} /><label>Full name<input name="name" required placeholder="Your name" /></label><label>Phone number<input name="phone" required placeholder="+256 ..." /></label><label>Email address<input name="email" type="email" placeholder="you@example.com" /></label><label>WhatsApp number<input name="whatsapp" placeholder="Optional" /></label><label>Service required<select name="service_required" defaultValue={service}><option value="">Choose a service</option>{services.map(([slug, name]) => <option key={slug} value={name}>{name}</option>)}</select></label><label>Destination<input name="destination_detail" defaultValue={destination} placeholder="Where are you going?" /></label><label>Travel date<input name="travel_date" type="date" /></label><label>Return date<input name="return_date" type="date" /></label><label>Travellers<input name="travellers" type="number" min="1" placeholder="1" /></label><label className="full">Additional information<textarea name="message" required rows="4" placeholder="Tell us a little about your plans..." /></label><button className="button" type="submit">Send enquiry <ArrowRight size={16} /></button>{error && <p className="form-error">{error}</p>}</form> }
function CtaBand({ title = 'Ready to make a plan?', text = 'Speak with the Altis Voyage team about your next journey.' }) { return <section className="platform-cta"><div><p className="eyebrow">Your next step</p><h2>{title}</h2><p>{text}</p></div><div><Link className="button" to="/contact">Make an enquiry <ArrowRight size={16} /></Link><WhatsApp /></div></section> }
function CardGrid({ items, kind }) { const images = useSiteImages(); return <div className={`${kind}-grid platform-card-grid`}>{items.map(item => { const [slug, name, third, fourth, description, file] = item; const href = kind === 'destination' ? `/destinations/${slug}` : `/tours/${slug}`; return <article className="platform-card" key={slug}><Img src={resolveImage(`${kind === 'destination' ? 'destinations' : 'tours'}/${file}`, images)} alt={`${name}, ${third}`} /><div><p className="card-kicker">{kind === 'destination' ? third : `${third} · ${fourth}`}</p><h3>{name}</h3><p>{kind === 'destination' ? fourth : description}</p><Link to={href}>Explore <ArrowRight size={15} /></Link></div></article> })}</div> }
function Home() { return <><Meta title="Travel beautifully considered" description="Altis Voyage Travel Services Ltd provides professional travel solutions from Kampala, Uganda." /><section className="platform-home-hero" style={{ backgroundImage: `linear-gradient(90deg,rgba(6,23,45,.96),rgba(6,23,45,.38)),url(${image('hero/lake-bunyonyi.svg')})` }}><div><p className="eyebrow">Altis Voyage Travel Services Ltd</p><h1>Travel with<br /><em>intention.</em></h1><p>Professional travel solutions from Kampala, Uganda, shaped around the way you want to move.</p><div className="hero-actions"><Link className="button" to="/contact">Plan your trip <ArrowRight size={16} /></Link><Link className="text-button" to="/destinations">Discover Uganda <ArrowRight size={16} /></Link></div></div></section><section className="quick-services"><p className="tag">What can we arrange?</p>{services.slice(0, 6).map(([slug, name]) => <Link key={slug} to={`/services/${slug}`}>{name}<ArrowRight size={14} /></Link>)}</section><section className="platform-section intro-platform"><div><p className="tag">01 / Travel support</p><h2>Good journeys begin with good questions.</h2></div><div><p>Altis Voyage Travel Services Ltd is a professional travel management company based in Kampala, Uganda. We provide flight reservations, visa assistance, hotel bookings, holiday packages, travel insurance, airport transfers, and corporate travel solutions.</p><Link className="inline" to="/about">Meet Altis Voyage <ArrowRight size={16} /></Link></div></section><section className="platform-section light-platform"><div className="section-heading"><div><p className="tag">02 / Featured destinations</p><h2>Find your way into Uganda.</h2></div><Link className="inline" to="/destinations">View all destinations <ArrowRight size={16} /></Link></div><CardGrid items={destinations} kind="destination" /></section><section className="platform-section"><div className="section-heading"><div><p className="tag">03 / Considered itineraries</p><h2>Start with a feeling.</h2></div><Link className="inline" to="/tours">Browse tours <ArrowRight size={16} /></Link></div><CardGrid items={tours} kind="tour" /></section><CtaBand title="Let’s make a good plan." text="Tell us what you are curious about. We will come back with a first sketch, not a sales pitch." /></> }
function About() { return <><Meta title="About us" description="Learn about Altis Voyage Travel Services Ltd, a professional travel company based in Kampala, Uganda." /><PageHero eyebrow="About Altis Voyage" title="Travel made personal." text="Professional, considered travel support from Kampala to the world." /><section className="platform-section split-copy"><div><p className="tag">Our company</p><h2>Built around the details that make travel feel easy.</h2><p>Altis Voyage Travel Services Ltd provides professional travel management from Kampala, Uganda. Our services include flight reservations, visa assistance, hotel bookings, holiday packages, travel insurance, airport transfers, and corporate travel solutions.</p></div><div className="fact-stack"><article><b>Mission</b><p>To provide exceptional travel services through professionalism, integrity, innovation, and customer-focused solutions.</p></article><article><b>Vision</b><p>To become one of Africa's most trusted and preferred travel service providers.</p></article><article><b>Our team</b><p><strong>BUHIGIRO OLIVIER</strong> — Marketing<br /><strong>NISHIMWE CYNTHIA</strong> — Director</p></article></div></section><CtaBand title="Travel with a team in your corner." /></> }
function Services() { return <><Meta title="Travel services" description="Explore Altis Voyage travel services including flights, visas, hotels, tours, transfers and corporate travel." /><PageHero eyebrow="Our services" title="Everything you need to go further." text="One trusted point of contact for the important details of travel." /><section className="platform-section light-platform"><div className="service-grid">{services.map(([slug, name, text], index) => <article className="service-panel" key={slug}><span>0{index + 1}</span><h2>{name}</h2><p>{text}</p><Link to={`/services/${slug}`}>Learn about this service <ArrowRight size={15} /></Link></article>)}</div></section><CtaBand /></> }
function ServiceDetail({ slug }) { const item = services.find(service => service[0] === slug) || services[0]; const [id, name, intro] = item; const isVisa = id === 'visa-assistance'; return <><Meta title={name} description={`${name} from Altis Voyage Travel Services Ltd in Kampala, Uganda.`} /><PageHero eyebrow="Altis Voyage service" title={name} text={intro} imagePath={id === 'airport-transfers' ? 'hero/sunset-savanna.svg' : 'hero/lake-bunyonyi.svg'} /><section className="platform-section split-copy"><div><p className="tag">How we help</p><h2>Clear support for the next step.</h2><p>{intro} Tell us what you need and our team will help shape the right enquiry around your dates, preferences, and travel plans.</p>{isVisa && <p className="notice">Visa decisions are made by the relevant authorities. Our role is to provide guidance and application support, not to promise approval.</p>}</div><div className="process-list"><div><span>01</span><b>Share your requirements</b><p>Send the details that matter for your journey.</p></div><div><span>02</span><b>Review the options</b><p>We respond with a clear, practical next step.</p></div><div><span>03</span><b>Move forward with confidence</b><p>Keep our team in your corner as plans take shape.</p></div></div></section><section className="platform-section light-platform"><EnquiryForm service={name} /></section><CtaBand title="Prefer a quick conversation?" /></> }
function DestinationDetail({ slug }) { const item = destinations.find(destination => destination[0] === slug) || destinations[0]; const [, name, country, description, file] = item; return <><Meta title={name} description={`${name}, ${country}: plan a considered trip with Altis Voyage.`} /><PageHero eyebrow={`${country} / Destination`} title={name} text={description} imagePath={`destinations/${file}`} /><Breadcrumbs current={name} /><section className="platform-section split-copy"><div><p className="tag">Destination notes</p><h2>A place to begin the conversation.</h2><p>{description} This destination page is structured for Altis Voyage to add confirmed travel details, activities, planning notes, and supplied imagery as content becomes available.</p></div><div className="placeholder-panel"><span>Content-ready structure</span><h3>Experiences, planning information and gallery</h3><p>Destination-specific facts and recommendations can be added here from the approved content source.</p></div></section><section className="platform-section light-platform"><div className="section-heading"><div><p className="tag">Related travel</p><h2>Packages to consider.</h2></div></div><CardGrid items={tours.filter(tour => tour[2].toLowerCase().includes(name.toLowerCase()) || name === 'Bwindi')} kind="tour" /></section><section className="platform-section"><EnquiryForm destination={name} /></section></> }
function Destinations() { return <><Meta title="Destinations" description="Discover destination planning with Altis Voyage Travel Services Ltd in Kampala, Uganda." /><PageHero eyebrow="Where to go" title="Find your way into Uganda." text="Destination discovery with space to plan around what matters to you." /><section className="platform-section light-platform"><div className="section-heading"><div><p className="tag">Featured destinations</p><h2>Places worth asking about.</h2></div><WhatsApp /></div><CardGrid items={destinations} kind="destination" /></section><CtaBand title="Have somewhere else in mind?" /></> }
function Tours() { return <><Meta title="Tours and packages" description="Explore tours, safaris and holiday package enquiries from Altis Voyage in Kampala." /><PageHero eyebrow="Tours & packages" title="Journeys built around you." text="Start with an idea, then let our team help shape the details." imagePath="hero/sunset-savanna.svg" /><section className="platform-section light-platform"><div className="section-heading"><div><p className="tag">Available structures</p><h2>Considered ways to travel.</h2></div></div><CardGrid items={tours} kind="tour" /><p className="content-note">Package prices, itineraries, accommodation and terms are added only when officially supplied.</p></section><CtaBand /></> }
function TourDetail({ slug }) { const item = tours.find(tour => tour[0] === slug) || tours[0]; const [, name, destination, duration, description, file] = item; return <><Meta title={name} description={`${name} travel package enquiry with Altis Voyage.`} /><PageHero eyebrow={`${destination} / ${duration}`} title={name} text={description} imagePath={`tours/${file}`} /><Breadcrumbs current={name} /><section className="platform-section split-copy"><div><p className="tag">Package overview</p><h2>A framework for your enquiry.</h2><p>{description}</p><p className="notice">Detailed pricing, itinerary, inclusions, exclusions, accommodation, transport and terms will be shown here when officially supplied.</p></div><div className="placeholder-panel"><span>{duration}</span><h3>{destination}</h3><p>Request the current package details from the Altis Voyage team.</p><WhatsApp>Ask about this trip</WhatsApp></div></section><section className="platform-section light-platform"><EnquiryForm service={name} destination={destination} /></section></> }
function SpecialPage({ type }) { const pages = { honeymoon: ['Honeymoon travel', 'Plan a beautiful beginning.', 'Thoughtful travel planning for couples, built around your pace and priorities.'], 'corporate-travel': ['Corporate travel', 'Keep business moving.', 'Corporate travel management support for flights, hotels, transfers and coordination.'], 'airport-transfers': ['Airport transfers', 'Arrive with less to think about.', 'Pick-up and drop-off planning for travellers moving through Kampala and beyond.'], 'travel-insurance': ['Travel insurance', 'Travel with more peace of mind.', 'Practical guidance on travel insurance enquiries before you take off.'], 'family-reunification': ['Family reunification', 'Make the journey back to each other.', 'Dedicated travel guidance for diaspora families planning to reconnect.'], 'why-choose-us': ['Why choose Altis Voyage', 'Professional support, personally delivered.', 'A professional team, competitive fares, personalized service, fast response times, reliable travel support and global travel solutions.'] }; const page = pages[type] || pages.honeymoon; return <><Meta title={page[0]} description={page[2]} /><PageHero eyebrow="Altis Voyage" title={page[1]} text={page[2]} imagePath="hero/sunset-savanna.svg" /><section className="platform-section split-copy"><div><p className="tag">{page[0]}</p><h2>Support that starts with listening.</h2><p>{page[2]} Share your requirements and the team will help you understand the next step without unsupported promises or hidden assumptions.</p></div><div className="benefit-list">{['Professional team','Competitive fares','Personalized service','Fast response times','Reliable travel support','Global travel solutions'].map(value => <div key={value}><Check size={17} />{value}</div>)}</div></section><section className="platform-section light-platform"><EnquiryForm service={page[0]} /></section><CtaBand title="Talk through your plans." /></> }
function Faq() { return <><Meta title="Frequently asked questions" description="Answers to common Altis Voyage travel service questions." /><PageHero eyebrow="Help centre" title="Questions before you go?" text="A clear starting point for common travel service enquiries." /><section className="platform-section faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={17} /></summary><p>{answer}</p></details>)}</section><CtaBand /></> }
function Gallery() { const [images, setImages] = useState([]); const [selected, setSelected] = useState(null); useEffect(() => { fetch(`${API}/api/images`).then(response => response.json()).then(data => setImages(data.gallery || [])).catch(() => {}) }, []); const fallback = ['gallery-1.svg', 'gallery-2.svg', 'gallery-3.svg', 'gallery-4.svg'].map((file, id) => ({ id, url: `/images/gallery/${file}`, caption: 'Altis Voyage travel image' })); const gallery = images.length ? images : fallback; return <><Meta title="Gallery" description="Explore the travel imagery and experiences connected with Altis Voyage." /><PageHero eyebrow="Gallery" title="Postcards from the road." text="A growing collection of destinations, journeys and travel moments." /><section className="platform-section light-platform"><div className="platform-gallery">{gallery.map((item, index) => <button key={item.id || index} onClick={() => setSelected(item)}><Img src={item.url} alt={item.caption || `Altis Voyage travel image ${index + 1}`} /></button>)}</div></section>{selected && <div className="platform-lightbox" onClick={() => setSelected(null)}><button aria-label="Close image"><X /></button><Img src={selected.url} alt={selected.caption} /></div>}<CtaBand title="Have a journey in mind?" /></> }
function Resources() { return <><Meta title="Travel resources" description="A future-ready home for Altis Voyage travel tips and destination guides." /><PageHero eyebrow="Travel resources" title="Useful things to know before you go." text="A future-ready space for approved travel tips, destination guides and planning notes." /><section className="platform-section light-platform resource-grid">{['Travel tips','Destination guides','Visa information','Flight travel tips','Holiday planning','Safari planning','Honeymoon ideas','Corporate travel advice'].map((title, index) => <article key={title}><span>0{index + 1}</span><h2>{title}</h2><p>Content-ready area for an approved Altis Voyage resource.</p></article>)}</section><CtaBand /></> }
function Legal({ type }) { const title = type === 'privacy-policy' ? 'Privacy policy' : 'Terms and conditions'; return <><Meta title={title} description={`${title} for Altis Voyage Travel Services Ltd.`} /><PageHero eyebrow="Information" title={title} text="This editable structure requires final review before publication." /><section className="platform-section legal-copy"><h2>{title}</h2><p>This page is a content-ready structure for Altis Voyage Travel Services Ltd. Final policy language should be reviewed and approved by the company before publication.</p><h3>Contact</h3><p>For questions, contact info@altistravels.com or bookings@altistravels.com.</p></section></> }
function Contact() { return <><Meta title="Contact us" description="Contact Altis Voyage Travel Services Ltd in Kampala for travel assistance." /><PageHero eyebrow="Contact centre" title="Let’s make a good plan." text="Find the team at Equatorial Mall, Level 3, Room 342, Bombo Road, Kampala, Uganda." /><section className="platform-section contact-platform"><div className="contact-details"><p className="tag">Reach us</p><h2>Altis Voyage Travel Services Ltd</h2><p><MapPin size={16} /> Equatorial Mall, Level 3, Room 342<br />Bombo Road, Kampala, Uganda<br />P.O. Box 210166 Kampala-Uganda</p><p><Phone size={16} /> <a href="tel:+256788748128">{phone}</a></p><p><MessageCircle size={16} /> <a href={whatsapp}>+256 774 497 295 / +256 756 037 524</a></p><p><Mail size={16} /> <a href="mailto:info@altistravels.com">info@altistravels.com</a><br /><a href="mailto:bookings@altistravels.com">bookings@altistravels.com</a></p></div><EnquiryForm /></section></> }
function PlatformApp() { return <Shell><Routes><Route path="/" element={<Home />} /><Route path="/about" element={<About />} /><Route path="/services" element={<Services />} /><Route path="/services/:slug" element={<ServiceRoute />} /><Route path="/destinations" element={<Destinations />} /><Route path="/destinations/:slug" element={<DestinationRoute />} /><Route path="/tours" element={<Tours />} /><Route path="/tours/:slug" element={<TourRoute />} /><Route path="/honeymoon" element={<SpecialPage type="honeymoon" />} /><Route path="/corporate-travel" element={<SpecialPage type="corporate-travel" />} /><Route path="/airport-transfers" element={<SpecialPage type="airport-transfers" />} /><Route path="/travel-insurance" element={<SpecialPage type="travel-insurance" />} /><Route path="/family-reunification" element={<SpecialPage type="family-reunification" />} /><Route path="/why-choose-us" element={<SpecialPage type="why-choose-us" />} /><Route path="/visa-assistance" element={<ServiceDetail slug="visa-assistance" />} /><Route path="/gallery" element={<Gallery />} /><Route path="/faq" element={<Faq />} /><Route path="/travel-resources" element={<Resources />} /><Route path="/privacy-policy" element={<Legal type="privacy-policy" />} /><Route path="/terms-and-conditions" element={<Legal type="terms-and-conditions" />} /><Route path="/contact" element={<Contact />} /><Route path="*" element={<Home />} /></Routes></Shell> }
function ServiceRoute() { const { slug } = useParams(); return <ServiceDetail slug={slug} /> }
function DestinationRoute() { const { slug } = useParams(); return <DestinationDetail slug={slug} /> }
function TourRoute() { const { slug } = useParams(); return <TourDetail slug={slug} /> }
export default PlatformApp
